### ISSUE TITLE
Use Alpine based images

### ISSUE THREAD

**Issue by drgomesp** [drgomesp/symfony-docker#10]
We should be using Alpine based images (https://github.com/gliderlabs/docker-alpine), which will reduce significantly the size overall.

**Comment by docteurklein** [comment]
I think using official images is far better than re-doing your own.

**Comment by drgomesp** [comment]
@docteurklein thanks for the reply, it's always great to have you around :)

Have you checked Alpine images? Comparing to the official images, these are the numbers:

```
REPOSITORY          TAG           IMAGE ID          VIRTUAL SIZE
gliderlabs/alpine   latest        157314031a17      5.03 MB
debian              latest        4d6ce913b130      84.98 MB
ubuntu              latest        b39b81afc8ca      188.3 MB
centos              latest        8efe422e6104      210 MB
```

It's quite amusing...

**Comment by docteurklein** [comment]
@drgomesp o/ hey there :)

yep, alpine brings interesting stuff, + a package manager for 5Mo.
I tried to make small images in the past too, but in the end, I prefer using official ones.

Almost every docker user has half the needed layers for a php image anyway.
In the end, you only end up downloading a small diff, not the whole layers of the image.

Thanks to COW, having a big image shouldn't be a big deal.
Now that's all theoretic, and I often hate having to wait for image pulls.
Nevertheless, I try to stick with maintainers recommendations: "stick to official images" :)
Otherwise, the public hub would be full of duplicates.

**Comment by docteurklein** [comment]
@drgomesp Another advantage of using the official images is that people won't be lost when entering a container (they will have apt-get, bash, …). Entering alpine can be intimidating at first.
If you have some special php extensions to install, you'll need a lot of shared libs, and finding these in debian is more documented than alpine.

Anway that's just my 2 cents.
I can totally see advantages to alpine too (mainly size) but also security :)

**Comment by cigoe** [comment]
There was a post on HN recently which had some good arguments for and against alpine at https://news.ycombinator.com/item?id=10782897

**Comment by drgomesp** [comment]
I'm convinced at this point. Let's close this and move on.

**Comment by drgomesp** [comment]
Reopening this, since I think there's still some discussion worth having.

For reference: http://www.iron.io/blog/2016/01/microcontainers-tiny-portable-containers.html

**Comment by docteurklein** [comment]
@drgomesp so, apparently we will have both from the best worlds :)
It seems they are moving official images to alpine. \o/
https://www.brianchristner.io/docker-is-moving-to-alpine-linux/

**Comment by ivoba** [comment]
I think we should make a distinction here between creating a dev box vs a prod box.
In my experience with docker as a dev box, its very likely that at some point you will enter the main symfony container and run symfony commands inside there instead of using 'docker-compose run'.
And in that case i would prefer to have a full distro like ubuntu, mainly to feel "at home".

For the linked containers like databases etc.  it would be fine to use alpine, i guess.

Another consideration would be to at least have a common base distro and dont mix debian for mysql, ubuntu for nginx and f.e. fedora for symfony. At the moment we have debian for the symfony container and tutum uses ubuntu. I guess this could also save us some layers.

**Comment by drgomesp** [comment]
Closing as it doesn't really matter. We're using `ubuntu` since we're mainly focused on dev environment.

**Comment by sergeyklay** [comment]
> we're mainly focused on dev environment.

https://github.com/drgomesp/symfony-docker/blob/master/README.md

> ready for development and production environments.

**Comment by drgomesp** [comment]
@sergeyklay I'll start to work on a distinction between dev and prod environments. For now, we're focused on having a full dev env working. Once we achieve that, we can focus on the production one.

**Comment by docteurklein** [comment]
but then you lose isomorphism (dev/prod parity)?

**Comment by drgomesp** [comment]
I guess we need to reopen this issue then, @docteurklein :)
