### ISSUE TITLE
Replace supervisord by runit

### ISSUE THREAD

**Issue by joelwurtz** [drgomesp/symfony-docker#12]
According to this (and also my experience) http://jtimberman.housepub.org/blog/2012/12/29/process-supervision-solved-problem/

Supervisord does not work so well being the PID 1, runit is IMO a better approach, also it reduces a lot the size of the image (very few dependencies)

I can make a PR if you want.

**Comment by drgomesp** [comment]
@joelwurtz that's a good suggestion, and a PR is always welcome and appreciated.

Please make sure, though, to have a look at the discussion  #13  regarding splitting the containers, because I think that could potentially defeat the purpose of having a process supervisor.

Feel free to explain me otherwise.

**Comment by mathewpeterson** [comment]
I don't believe this issues is valid anymore.
