### ISSUE TITLE
Consider to use a different container for NGINX

### ISSUE THREAD

**Issue by henriquemoody** [drgomesp/symfony-docker#7]
Since you're using PHP-FPM, is that necessary to have NGINX on the same container of PHP?

**Comment by drgomesp** [comment]
Not really necessary, but I don't really see the point of separating them for such a simple structure – unless you're thinking of maybe running different containers for different PHP versions or any other reason. But TBH it wouldn't be such a hard thing to do...

**Comment by henriquemoody** [comment]
The point is there is already a image (official) for [NGINX](https://hub.docker.com/_/nginx/), the only thing you must to is to point the CGI to the PHP image on NGINX configuration file.

If you use a different container :
- You reuse NGINX image, since you can have other applications that also use NGINX, then you don't have to build images with NGINX multiple times;
- You reduce the size of your PHP image;
- You reduce the time of the build, which I know is fast already but can be better.

**Comment by drgomesp** [comment]
Ok, you convinced me. Want to jump in? :8ball:

**Comment by mathewpeterson** [comment]
Feel free to use my template: https://github.com/mathewpeterson/docker-nginx-mysql-php

I can also submit a PR if you would like.

**Comment by drgomesp** [comment]
@mathewpeterson that would be greatly appreciated! Just don't forget we're using supervisord to startup everything.

**Comment by henriquemoody** [comment]
If you use a different container for NGINX supervisord will be no longer necessary

**Comment by mathewpeterson** [comment]
If you would like to chat about this outside of github, consider joining https://symfony2slack.herokuapp.com/.

**Comment by docteurklein** [comment]
I agree with @henriquemoody , using supervisord in docker is usually a "code smell".
docker's native restart strategy is OK if you separate correctly the processes in different containers.

**Comment by drgomesp** [comment]
@docteurklein I tend to agree. Want to jump in with a PR? ;)

**Comment by docteurklein** [comment]
@drgomesp I can try to find some time :) But I wouldn't want to interfer with @mathewpeterson :)

**Comment by mathewpeterson** [comment]
Here is my WIP: https://github.com/drgomesp/symfony-docker/compare/master...mathewpeterson:feature/separate-containers?expand=1

**Comment by EHER** [comment]
@mathewpeterson :+1: 

I'm also using different containers here: https://github.com/EHER/voluntarios/blob/master/docker-compose.yml

**Comment by drgomesp** [comment]
@EHER good example :+1: 

@mathewpeterson do you want to open a PR?

**Comment by joelwurtz** [comment]
I don't agree on separating nginx from php-fpm, it really depend on the use case. 

If you consider the symfony application rendering dynamic files and also static files then nginx and php-fpm should be in the same container (nginx use to serve static content, and php-fpm for php).

If you consider the symfony application only rendering php files (no css/ no js) then yes only the php-fpm is needed.

This vision is 1 Service = 1 Container (not 1 process), and you can always throws a nginx in top of this which will act as a router for multiple applications (but will be better to use haproxy for this use case)

**Comment by docteurklein** [comment]
@joelwurtz putting the 2 processes in the same container just because of serving assets is not the best excuse.
A contrario, I would say it proves that assets shouldn't be part of the php application :)

What I do personally is to put the static assets in the nginx container, at image build time.

**Comment by joelwurtz** [comment]
Yeah but really depend on the vision you give to your application.

> A contrario, I would say it proves that assets shouldn't be part of the php application :)

It depends on the application if you have something simple enough or very tied, separating asset from your php application can be a nightmare and bring uneeded complexity to your infrastructure.

IMO, most of the times, the application is a service who is reponsible to deliver html and related ressources, and in this case i prefer to have 1 container.

However like a said if you want to serve assets not within a php application (like having a cdn service) yes it should be separated

Also agree on supervisord part from you previous comment, he is not good as acting as a process manager see #12

**Comment by mathewpeterson** [comment]
I created a PR and gave my reasoning why I've separated the containers.

**Comment by mathewpeterson** [comment]
For verbosity: @joelwurtz I agree with @docteurklein. Your statements do not reflect Docker best practices. While you can do what ever you want with your projects, I would like to adhere to Docker best practices.

**Comment by joelwurtz** [comment]
Point of having 1 process per container in the best practice is for reusabilty and scalability like they said, so for me the best practice is incorrect with the term "process" and should be "service" (and BTW they are using service word afterwards)

A service can be represented by one or more process, that's not the point. Like if you have some sort of auto generated config file with [dockergen](https://github.com/jwilder/docker-gen) you would have 2 processes but the second process is just a helper for the first one.

The rule 1 process = 1 container is also because in 99% use case a process represent a service, but for me that's not the case with nginx and php-fpm as this 2 processes represent our "web" service (unless you separate assets management to a cdn service) and this is this "web" service (with the 2 process) which should be scaled.

It's also better for production, as actually you link the root folder of this repository to the container, but in a production usage you would use the `COPY` keyword from Dockerfile to put your application into the container to make it environment agnostic and have a better deployment workflow, if you use this approach of separating these 2 process but in fact there are for the same service then you will loose consistency for you service :/.

**Comment by joelwurtz** [comment]
BTW i don't say that you must not do that or anything, just want to bring another point of view for this.

**Comment by docteurklein** [comment]
@joelwurtz interesting discussion :)
I agree generally with your points, but 2 things got me:

> this "web" service (with the 2 process) which should be scaled.

Usually you don't scale nginx linearly with fpm.
More often than not, 1 nginx will load-balance to many FPM backends.
It's rare to have a 1-1 mapping between nginx and fpm,
so it makes sense to separate them to scale them independantly.

> you link the root folder of this repository to the container, but in a production usage you would use the COPY keyword from Dockerfile to put your application into the container to make it environment agnostic […]

Now there is a certain coupling between nginx and fpm because of the fcgi variables (scriptname) which must have knowledge about the remote filesystem.
So indeed, having both processes on the same filesystem (container) can help.
But using volumes or COPY don't change anything to this coupling.

And yeah, like you said, I'm totally OK with both POVs :) just sharing my thoughts :) o/

**Comment by joelwurtz** [comment]
> Usually you don't scale nginx linearly with fpm.

Nginx for me in this context only act as an helper for transforming web request to the cgi process of php-fpm so it's configured linearly with fpm, if i want to scale, i scale the containers.

> So indeed, having both processes on the same filesystem (container) can help.
> But using volumes or COPY don't change anything to this coupling.

Hum it's more about reloading and inconsistency within the service, like on a high loaded backend you would use hot reloading of your services and maybe reload them one by one. Not having this coupling can bring desynchronisation and bugs if your application is very tied to your assets (like using assetic or anything else)

Also I use this approach because i don't like to use nginx as the router (i use haproxy most of the times) and delivering a web service with only fastcgi does not make sense in this vision (no browser can use it obviously): i like my services to be able to be independent from the others.

**Comment by joelwurtz** [comment]
Also only scaling php-fpm is hard to do because only nginx is able to access it, having both of the process in the container make it simpler because you scale a http service, and there is a LOT of tools to facilite this without having to reimplement everything

**Comment by mathewpeterson** [comment]
> Also only scaling php-fpm is hard to do because only nginx is able to access it, having both of the process in the container make it simpler because you scale a http service, and there is a LOT of tools to facilite this without having to reimplement everything

What? Do you have any data to back that statement up?

**Comment by joelwurtz** [comment]
Yes wrong about the "nginx" part, it's only tools which can interact with cgi and be able to access the php-fpm process, there are not so many tools for that (i can think of nginx / apache / lighthttpd).

So if you want to scale the php-fpm service you would need to change your configuration for the load balancer transforming http request to cgi process (nginx in this case). And in my view there are not so many tools to do that (you can use dockergen but i find it a little bit hackish) and if you want hot reloading it's even harder. 

Accepting directly a HTTP request on this container is easier because the number tools and documentation about scaling http request is gigantic and there is a lot of choices and best practice around it like [Traefik](https://github.com/emilevauge/traefik), [haproxy](http://www.haproxy.org/), ...

But nginx may not be the best choice to only serve as a converter from http request to cgi, if there is a good (and light) tool about that, I'm more than interrested!

**Comment by drgomesp** [comment]
I agree with both @mathewpeterson and @docteurklein in the sense that it's better for the processes to be separated per container – although I appreciate your comments, @joelwurtz, and I see the point your trying to make.

For me, the main advantage is being able to swap between different PHP(-FPM) versions rapidly.

Let's continue the discussion and decide on the strategy we prefer, since that's going to drive the way this package will be maintained in the future.

**Comment by joelwurtz** [comment]
> For me, the main advantage is being able to swap between different PHP(-FPM) versions rapidly.

I think you can still use a base php image and add nginx on top of it, to have this feature

Also, you should maybe consider set 0 children to the php-fpm process to really have 1 process (which will be the fpm master process with no children) to really respect the 1 process = 1 container :-°

Troll aside, i'm still thinking that nginx is too really tied with php-fpm to really have it outside another container, as if you want to scale your php-fpm you will have to change your nginx configuration or scale it in the same way. Futhermore your nginx configuration can contain application rules (like redirection, htpasswd, other stuffs ...) which really indicate that this is the same service.

(And if you want autoscaling you will have to use dockergen which will be another process to run with your nginx, which also break the rule of one process = one container)

Last complaint on this :) don't want to take too much of your time, but i will maybe make a fork with my vision, as IMO this is a bad practice.

**Comment by mathewpeterson** [comment]
This should be resolved by #13

**Comment by drgomesp** [comment]
Closed by #13
